### ISSUE TITLE
REDIS_PASSWORD

### ISSUE THREAD

**Issue by guoyoujin** [sameersbn/docker-redis#6]
docker-compose.yml file inside how to set REDIS_PASSWORD

**Comment by GJRTimmer** [comment]
```yaml
Redis:
  image: sameersbn/redis:latest
  ports:
    - "6379:6379"
  environment:
    - REDIS_PASSWORD=your_password
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always
```
